"""
Model Accuracy Dashboard — displays historical prediction performance metrics.

Shows:
- Brier score over time (primary metric for probabilistic predictions)
- Log-loss trends
- Calibration curves
- Platt scaling parameters
- Sample sizes per season

Data source: data/historical/model_accuracy_*.json
Generated by: scripts/recalibrate_model.py
"""

import streamlit as st
import json
import pandas as pd
from pathlib import Path
from typing import List, Dict, Any


def load_accuracy_metrics() -> List[Dict[str, Any]]:
    """Load all model accuracy JSON files from historical directory."""
    hist_dir = Path(__file__).parent.parent / "data" / "historical"
    if not hist_dir.exists():
        return []
    
    metrics_files = sorted(hist_dir.glob("model_accuracy_*.json"))
    all_metrics = []
    
    for mf in metrics_files:
        try:
            with open(mf, 'r') as f:
                data = json.load(f)
                all_metrics.append(data)
        except Exception as e:
            st.warning(f"Failed to load {mf.name}: {e}")
    
    return all_metrics


def show():
    st.set_page_config(page_title="Model Accuracy", page_icon="📊", layout="wide")
    
    st.title("📊 Model Accuracy Tracking")
    st.markdown("""
    **Brier Score** is the most important metric for a probabilistic prediction system.
    - Lower is better (perfect = 0.0, random ≈ 0.25)
    - Measures mean squared error between predicted probabilities and actual outcomes
    - Well-calibrated models typically achieve < 0.05 for win predictions
    
    **Log-Loss** penalizes confident wrong predictions more heavily.
    - Lower is better
    - More sensitive to extreme probability errors than Brier score
    """)
    
    # Load metrics
    all_metrics = load_accuracy_metrics()
    
    if not all_metrics:
        st.info("🔍 No historical accuracy data found yet.")
        st.markdown("""
        **To generate accuracy metrics:**
        ```bash
        python scripts/recalibrate_model.py --season 2026
        ```
        
        This will:
        1. Run temporal cross-validation on completed races
        2. Compute Brier scores and log-loss
        3. Generate calibration curves
        4. Save results to `data/historical/model_accuracy_2026.json`
        """)
        return
    
    # Display latest metrics prominently
    latest = all_metrics[-1]
    col1, col2, col3, col4 = st.columns(4)
    
    with col1:
        status_icon = "✅" if latest.get("status") == "well_calibrated" else "⚠️"
        st.metric(
            "Latest Status",
            f"{status_icon} {latest.get('status', 'N/A').replace('_', ' ').title()}"
        )
    
    with col2:
        win_brier = latest.get("metrics", {}).get("win_brier_score", None)
        if win_brier is not None:
            color = "green" if win_brier < 0.04 else "orange" if win_brier < 0.07 else "red"
            st.metric(
                "Win Brier Score",
                f"{win_brier:.4f}",
                delta="Excellent" if win_brier < 0.04 else "Good" if win_brier < 0.07 else "Needs Review",
                delta_color="normal" if win_brier < 0.07 else "inverse"
            )
    
    with col3:
        top3_brier = latest.get("metrics", {}).get("top3_brier_score", None)
        if top3_brier is not None:
            st.metric(
                "Top-3 Brier Score",
                f"{top3_brier:.4f}",
                delta="Excellent" if top3_brier < 0.12 else "Good" if top3_brier < 0.20 else "Review",
                delta_color="normal" if top3_brier < 0.20 else "inverse"
            )
    
    with col4:
        sample_size = latest.get("metrics", {}).get("sample_size", 0)
        st.metric("Sample Size", f"{sample_size:,} predictions")
    
    st.divider()
    
    # Historical trends across seasons
    if len(all_metrics) > 1:
        st.subheader("📈 Historical Trends")
        
        trend_data = []
        for m in all_metrics:
            trend_data.append({
                "Season": m.get("season"),
                "Win Brier": m.get("metrics", {}).get("win_brier_score"),
                "Top-3 Brier": m.get("metrics", {}).get("top3_brier_score"),
                "Win Log-Loss": m.get("metrics", {}).get("win_log_loss"),
                "Sample Size": m.get("metrics", {}).get("sample_size"),
            })
        
        df_trend = pd.DataFrame(trend_data)
        
        col1, col2 = st.columns(2)
        with col1:
            st.line_chart(df_trend.set_index("Season")[["Win Brier", "Top-3 Brier"]])
        with col2:
            st.line_chart(df_trend.set_index("Season")[["Win Log-Loss"]])
    
    st.divider()
    
    # Detailed metrics for selected season
    st.subheader("🎯 Season Details")
    
    seasons = [m.get("season") for m in all_metrics]
    selected_season = st.selectbox("Select Season", seasons, index=len(seasons)-1)
    
    selected_metrics = next((m for m in all_metrics if m.get("season") == selected_season), None)
    
    if selected_metrics:
        col1, col2 = st.columns(2)
        
        with col1:
            st.markdown("### Win Prediction Metrics")
            metrics_win = selected_metrics.get("metrics", {})
            
            st.metric("Brier Score", f"{metrics_win.get('win_brier_score', 'N/A'):.4f}")
            st.metric("Log-Loss", f"{metrics_win.get('win_log_loss', 'N/A'):.4f}")
            
            platt = metrics_win.get("platt_scaling", {}).get("win", {})
            st.caption(f"Platt Scaling: A={platt.get('A', 'N/A')}, B={platt.get('B', 'N/A')}")
        
        with col2:
            st.markdown("### Top-3 Prediction Metrics")
            st.metric("Brier Score", f"{metrics_win.get('top3_brier_score', 'N/A'):.4f}")
            st.metric("Log-Loss", f"{metrics_win.get('top3_log_loss', 'N/A'):.4f}")
            
            platt_top3 = metrics_win.get("platt_scaling", {}).get("top3", {})
            st.caption(f"Platt Scaling: A={platt_top3.get('A', 'N/A')}, B={platt_top3.get('B', 'N/A')}")
        
        # Calibration curve
        st.divider()
        st.subheader("📉 Calibration Curve")
        
        cal_curve = selected_metrics.get("calibration_curve", [])
        if cal_curve:
            df_cal = pd.DataFrame(cal_curve)
            
            fig_col1, fig_col2 = st.columns(2)
            
            with fig_col1:
                st.line_chart(
                    df_cal.set_index("bin")[["mean_predicted", "actual_rate"]],
                    use_container_width=True
                )
                st.caption("Perfect calibration: predicted rate = actual rate (lines should overlap)")
            
            with fig_col2:
                st.bar_chart(
                    df_cal.set_index("bin")[["n"]],
                    use_container_width=True
                )
                st.caption("Sample size per probability bin")
            
            # Calibration error table
            st.dataframe(
                df_cal[["bin", "n", "mean_predicted", "actual_rate", "calibration_error"]],
                use_container_width=True,
                hide_index=True
            )
        else:
            st.info("No calibration curve data available for this season.")
    
    st.divider()
    
    # Interpretation guide
    with st.expander("📖 How to interpret these metrics"):
        st.markdown("""
        ### Brier Score Interpretation
        
        | Range | Quality | Meaning |
        |-------|---------|---------|
        | < 0.04 | ✅ Excellent | Model is very well-calibrated |
        | 0.04–0.07 | ⚠️ Good | Acceptable but could improve |
        | > 0.07 | ❌ Poor | Model needs recalibration |
        
        ### What affects Brier Score?
        
        - **Safety Car Probability**: High SC circuits (Canada, Singapore) are harder to predict
        - **Rain**: Wet races introduce more variance
        - **Rookie Drivers**: Less historical data → higher uncertainty
        - **New Circuits**: Madrid 2026 has no historical wins data
        
        ### When to Recalibrate
        
        Run `python scripts/recalibrate_model.py` when:
        - Every 4-6 races during the season
        - After major regulation changes
        - If Brier score exceeds 0.07 consistently
        - Before making significant FEATURE_WEIGHTS adjustments
        
        ### Platt Scaling
        
        Used to calibrate raw model outputs to better match observed frequencies.
        - A ≈ 1.0, B ≈ 0.0 means model is already well-calibrated
        - Large deviations suggest systematic bias needing correction
        """)


if __name__ == "__main__":
    show()
